# Generated by Django 5.0 on 2023-12-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_course_category_course_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('slogan', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(to='mainapp.coursecategories'),
        ),
    ]
