# Generated by Django 5.0 on 2023-12-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_coursecategories_delete_coursecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, to='mainapp.coursecategories'),
        ),
    ]
