# Generated by Django 5.0 on 2023-12-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_course_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slag',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='coursecategories',
            name='slag',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
