# Generated by Django 5.0 on 2023-12-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_course_slag_coursecategories_slag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecategories',
            old_name='slogan',
            new_name='tag',
        ),
    ]
