# Generated by Django 5.0 on 2023-12-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_slogan_coursecategories_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slag',
        ),
        migrations.RemoveField(
            model_name='coursecategories',
            name='slag',
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='course_slug', unique=True),
        ),
        migrations.AddField(
            model_name='coursecategories',
            name='slug',
            field=models.SlugField(default='category_slug', unique=True),
        ),
    ]
