# Generated by Django 5.0 on 2023-12-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_course_slag_remove_coursecategories_slag_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseCategories',
            new_name='CourseCategory',
        ),
    ]
